-- =============================================
-- SUPABASE DATA SEED
-- Copy and run in Supabase SQL Editor
-- =============================================


-- Insert Dojos
INSERT INTO public.dojos (id, name, chief_instructor, address, lat, lng, map_link, phone, email, image_url, description, status)
VALUES
(
      'iwama-honbu',
      'Iwama Shin-Shin Aiki Shuren-kai Honbu Dojo',
      'Hitohira Saito Sensei',
      '2289-1 Yoshioka, Iwama-machi, Kasama-shi, Ibaraki-ken 319-0203, Japan',
      36.3583,
      140.2864,
      'https://maps.google.com/?q=36.3583,140.2864',
      '+81-299-45-2224',
      'info@iwamaaikido.com',
      '/images/dojos/iwama-honbu.jpg',
      'The birthplace of Iwama style Aikido, where O-Sensei spent his later years developing the art in harmony with nature.',
      'approved'
    ),
(
      'tanrenkan-california',
      'Tanrenkan Dojo - California',
      'Miles Kessler Sensei',
      '1234 Aikido Way, San Francisco, CA 94102, USA',
      37.7749,
      -122.4194,
      'https://maps.google.com/?q=37.7749,-122.4194',
      '+1-415-555-0123',
      'info@tanrenkan-ca.org',
      '/images/dojos/tanrenkan-ca.jpg',
      'A traditional Iwama dojo bringing authentic teachings to the West Coast of America.',
      'approved'
    ),
(
      'takemusu-paris',
      'Takemusu Aiki Paris',
      'Daniel Toutain Sensei',
      '45 Rue de la Paix, 75002 Paris, France',
      48.8566,
      2.3522,
      'https://maps.google.com/?q=48.8566,2.3522',
      '+33-1-42-65-1234',
      'contact@takemusu-paris.fr',
      '/images/dojos/takemusu-paris.jpg',
      'One of the premier Iwama Aikido dojos in Europe, dedicated to preserving the founder''s teachings.',
      'approved'
    ),
(
      'iwama-sweden',
      'Iwama Ryu Sweden',
      'Ulf Evenas Sensei',
      'Drottninggatan 12, 111 51 Stockholm, Sweden',
      59.3293,
      18.0686,
      'https://maps.google.com/?q=59.3293,18.0686',
      '+46-8-555-1234',
      'info@iwama-sweden.se',
      '/images/dojos/iwama-sweden.jpg',
      'Bringing the spirit of Iwama to Scandinavia through dedicated practice and teaching.',
      'approved'
    ),
(
      'aiki-shuren-australia',
      'Aiki Shuren Dojo Melbourne',
      'Tony Smibert Sensei',
      '78 Collins Street, Melbourne VIC 3000, Australia',
      -37.8136,
      144.9631,
      'https://maps.google.com/?q=-37.8136,144.9631',
      '+61-3-9555-1234',
      'info@aikishuren-melbourne.com.au',
      '/images/dojos/aiki-shuren-australia.jpg',
      'Australia''s leading Iwama style dojo, fostering the next generation of aikidoka.',
      'approved'
    ),
(
      'takemusu-germany',
      'Takemusu Aikido Berlin',
      'Stefan Stenudd Sensei',
      'Unter den Linden 77, 10117 Berlin, Germany',
      52.52,
      13.405,
      'https://maps.google.com/?q=52.5200,13.4050',
      '+49-30-555-1234',
      'info@takemusu-berlin.de',
      '/images/dojos/takemusu-berlin.jpg',
      'A center of excellence for traditional Iwama Aikido in the heart of Europe.',
      'approved'
    )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  chief_instructor = EXCLUDED.chief_instructor,
  address = EXCLUDED.address,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  map_link = EXCLUDED.map_link,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  image_url = EXCLUDED.image_url,
  description = EXCLUDED.description;


-- Insert Techniques
INSERT INTO public.techniques (id, slug, type, name_jp, name_en, category, subcategory, difficulty, description, attack, base_technique, belt_levels, variants, content)
VALUES
(
      'tai-no-henko',
      'tai-no-henko',
      'foundational',
      '体の変更',
      'Body Change',
      'Taijutsu',
      'Warm-up',
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '["Kihon","Ki no Nagare"]',
      '{"key_postures":[{"title":"Kamae","description":"Stand in hanmi stance, facing partner."},{"title":"Receive Grab","description":"Partner grabs your wrist firmly."},{"title":"Tenkan","description":"Turn 180 degrees, rear foot steps in arc behind."}],"important_notes":[{"note":"Keep center low throughout the turn."},{"note":"Use hips to lead, not arm strength."}]}'
    ),
(
      'morotedori-kokyuho',
      'morotedori-kokyuho',
      'foundational',
      '諸手取り呼吸法',
      'Two-Hand Grab Breath Power',
      'Taijutsu',
      'Warm-up',
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Being Grabbed","description":"Partner uses both hands to grab one wrist."},{"title":"Extension","description":"Extend arm using hip and hara power."},{"title":"Throw","description":"Continue extension to throw partner."}],"important_notes":[{"note":"Coordinate breath: inhale to prepare, exhale to extend."}]}'
    ),
(
      'ikkyo',
      'ikkyo',
      'foundational',
      '一教',
      'First Teaching',
      'Taijutsu',
      'Osae Waza',
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Ai-hanmi Kamae","description":"Begin in matching stance with proper distance."},{"title":"Irimi Entry","description":"Enter deeply alongside partner''s arm."},{"title":"Osae Pin","description":"Guide partner down in spiral motion to mat."}],"important_notes":[{"note":"Never use force against force."},{"note":"Cutting motion originates from hips."}]}'
    ),
(
      'nikyo',
      'nikyo',
      'foundational',
      '二教',
      'Second Teaching',
      'Taijutsu',
      'Osae Waza',
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Wrist Grip","description":"Grip partner''s wrist in C-grip."},{"title":"Wrist Rotation","description":"Rotate wrist inward while controlling elbow."},{"title":"Kneeling Pin","description":"Bring partner down using wrist lock."}],"important_notes":[{"note":"Effectiveness comes from precise angle, not force."}]}'
    ),
(
      'sankyo',
      'sankyo',
      'foundational',
      '三教',
      'Third Teaching',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Hand Capture","description":"Capture partner''s hand with both hands."},{"title":"Spiral Rotation","description":"Rotate hand in spiral toward centerline."},{"title":"Standing Control","description":"Maintain lock for throw or pin."}],"important_notes":[{"note":"Spiral must be continuous and connected to center."}]}'
    ),
(
      'yonkyo',
      'yonkyo',
      'foundational',
      '四教',
      'Fourth Teaching',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Forearm Grip","description":"Grip forearm with knuckle on pressure point."},{"title":"Pressure Point","description":"Apply pressure while maintaining arm control."},{"title":"Lead Down","description":"Use combined control to lead partner down."}],"important_notes":[{"note":"Pressure point is 1-2 inches from wrist on inner forearm."}]}'
    ),
(
      'gokyo',
      'gokyo',
      'foundational',
      '五教',
      'Fifth Teaching',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Knife Defense","description":"Grip wrist with thumb facing down."},{"title":"Elbow Control","description":"Keep elbow extended and locked."},{"title":"Disarm and Pin","description":"Lead partner down while disarming."}],"important_notes":[{"note":"Reverse grip keeps knife blade away from you."}]}'
    ),
(
      'shihonage',
      'shihonage',
      'foundational',
      '四方投げ',
      'Four Directions Throw',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Katate-dori Grasp","description":"Blend while securing wrist with both hands."},{"title":"Tenkan Pivot","description":"180-degree pivot while raising arm overhead."},{"title":"Throw Completion","description":"Cut down with arm while stepping through."}],"important_notes":[{"note":"Iwama: hold hand like gripping sword in front of chest."}]}'
    ),
(
      'iriminage',
      'iriminage',
      'foundational',
      '入り身投げ',
      'Entering Throw',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Initial Entry","description":"Enter deeply past attack, hip connected to center."},{"title":"Spiral Drawing","description":"Draw partner in circular motion."},{"title":"Final Throw","description":"Enter again while guiding head backward."}],"important_notes":[{"note":"True irimi requires complete commitment."}]}'
    ),
(
      'kotegaeshi',
      'kotegaeshi',
      'foundational',
      '小手返し',
      'Wrist Return Throw',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Wrist Grip","description":"One hand on back of hand, other supporting."},{"title":"Wrist Turn","description":"Turn wrist outward and downward."},{"title":"Throw","description":"Continue turning to throw partner."}],"important_notes":[{"note":"Use entire body to create turning force."}]}'
    ),
(
      'kaitennage',
      'kaitennage',
      'foundational',
      '回転投げ',
      'Rotation Throw',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '["Uchi Kaiten-nage","Soto Kaiten-nage"]',
      '{"key_postures":[{"title":"Grip and Lead","description":"Grip arm and lead in arc."},{"title":"Rotation","description":"Uchi: under armpit. Soto: outside neck."},{"title":"Complete Throw","description":"Continue rotation to throw."}],"important_notes":[{"note":"Keep partner off-balance throughout rotation."}]}'
    ),
(
      'tenchinage',
      'tenchinage',
      'foundational',
      '天地投げ',
      'Heaven and Earth Throw',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Ryote-dori","description":"Partner grabs both wrists."},{"title":"Separation","description":"One hand to heaven, other to earth."},{"title":"Enter and Throw","description":"Step in while maintaining separation."}],"important_notes":[{"note":"Both hands move simultaneously."}]}'
    ),
(
      'kokyu-ho',
      'kokyu-ho',
      'foundational',
      '呼吸法',
      'Breath Power Exercise',
      'Taijutsu',
      'Warm-up',
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Seiza","description":"Both sit in seiza, partner grabs wrists."},{"title":"Extension","description":"Extend arms using hara power."},{"title":"Projection","description":"Break balance and push backward."}],"important_notes":[{"note":"Relax shoulders completely."}]}'
    ),
(
      'suburi-ichi',
      'suburi-ichi',
      'foundational',
      '素振り一',
      'First Sword Swing',
      'Aiki-Ken',
      NULL,
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Chudan Kamae","description":"Middle guard, tip at throat height."},{"title":"Raise","description":"Raise sword overhead in large arc."},{"title":"Cut","description":"Execute downward cut using center."}],"important_notes":[{"note":"Cut comes from center, not arms."}]}'
    ),
(
      'kumitachi-ichi',
      'kumitachi-ichi',
      'foundational',
      '組太刀一',
      'First Paired Sword',
      'Aiki-Ken',
      NULL,
      'Intermediate',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Opening Position","description":"Both in chudan kamae at proper distance."},{"title":"Attack and Response","description":"Uchitachi initiates, uketachi receives."},{"title":"Counter","description":"Uketachi completes with counter-cut."}],"important_notes":[{"note":"Uchitachi provides sincere attacks."}]}'
    ),
(
      'jo-suburi-ichi',
      'jo-suburi-ichi',
      'foundational',
      '杖素振り一',
      'First Staff Swing',
      'Aiki-Jo',
      NULL,
      'Beginner',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Choku-tsuki Kamae","description":"Hold jo pointing at throat."},{"title":"Prepare","description":"Draw jo back along centerline."},{"title":"Thrust","description":"Drive forward with rear foot."}],"important_notes":[{"note":"Thrust and footwork must be unified."}]}'
    ),
(
      'thirty-one-jo-kata',
      'thirty-one-jo-kata',
      'foundational',
      '三十一の杖',
      '31 Jo Kata',
      'Aiki-Jo',
      NULL,
      'Advanced',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Opening Sequence","description":"Begins with choku-tsuki."},{"title":"Middle Section","description":"Complex combinations including kaeshi-tsuki."},{"title":"Closing Sequence","description":"Decisive movements with proper zanshin."}],"important_notes":[{"note":"Learn each movement individually first."}]}'
    ),
(
      'tachi-dori',
      'tachi-dori',
      'foundational',
      '太刀取り',
      'Sword Taking',
      'Buki-dori',
      NULL,
      'Advanced',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Facing Sword","description":"Move to avoid the cut."},{"title":"Enter and Control","description":"Enter and control sword arm."},{"title":"Disarm","description":"Apply technique while disarming."}],"important_notes":[{"note":"Timing and irimi are critical."}]}'
    ),
(
      'jo-dori',
      'jo-dori',
      'foundational',
      '杖取り',
      'Staff Taking',
      'Buki-dori',
      NULL,
      'Advanced',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Facing Staff","description":"Move to avoid strike or thrust."},{"title":"Entry","description":"Enter inside staff''s reach."},{"title":"Disarm","description":"Apply technique to disarm."}],"important_notes":[{"note":"Jo has long reach, needs decisive entry."}]}'
    ),
(
      'tanto-dori',
      'tanto-dori',
      'foundational',
      '短刀取り',
      'Knife Taking',
      'Buki-dori',
      NULL,
      'Advanced',
      '',
      NULL,
      NULL,
      '[]',
      '[]',
      '{"key_postures":[{"title":"Facing Knife","description":"Most dangerous situation."},{"title":"Evade and Control","description":"Avoid and control knife-holding arm."},{"title":"Disarm with Gokyo","description":"Apply Gokyo to safely disarm."}],"important_notes":[{"note":"Reverse grip keeps blade away from you."}]}'
    ),
(
      'shomen-uchi-ikkyo',
      'shomen-uchi-ikkyo',
      'grading',
      '正面打ち一教',
      'Shomen Uchi Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Beginner',
      '',
      'shomen-uchi',
      'ikkyo',
      '["7th-kyu","6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Kamae","description":"Face partner in ai-hanmi stance."},{"title":"Receive Strike","description":"Blend and enter as partner strikes shomen-uchi."},{"title":"Apply Ikkyo","description":"Control elbow and wrist, guide to ground."}],"important_notes":[{"note":"Maintain proper maai throughout."}]}'
    ),
(
      'yokomen-uchi-ikkyo',
      'yokomen-uchi-ikkyo',
      'grading',
      '横面打ち一教',
      'Yokomen Uchi Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Beginner',
      '',
      'yokomen-uchi',
      'ikkyo',
      '["5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Kamae","description":"Face partner in gyaku-hanmi stance."},{"title":"Receive Strike","description":"Enter diagonally to intercept yokomen strike."},{"title":"Apply Ikkyo","description":"Control arm and guide partner down."}],"important_notes":[{"note":"Enter early to intercept the strike."}]}'
    ),
(
      'katadori-ikkyo',
      'katadori-ikkyo',
      'grading',
      '肩取り一教',
      'Katadori Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'katadori',
      'ikkyo',
      '["4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Allow partner to grab shoulder."},{"title":"Break Balance","description":"Enter and unbalance partner."},{"title":"Apply Ikkyo","description":"Transition to ikkyo control."}],"important_notes":[{"note":"Use hip rotation to generate power."}]}'
    ),
(
      'ryotedori-ikkyo',
      'ryotedori-ikkyo',
      'grading',
      '両手取り一教',
      'Ryotedori Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'ryotedori',
      'ikkyo',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Both wrists grabbed."},{"title":"Break Hold","description":"Use body movement to disrupt grip."},{"title":"Apply Ikkyo","description":"Transition to ikkyo on one arm."}],"important_notes":[{"note":"Move the whole body, not just arms."}]}'
    ),
(
      'morotedori-ikkyo',
      'morotedori-ikkyo',
      'grading',
      '諸手取り一教',
      'Morotedori Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'morotedori',
      'ikkyo',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Two hands on one wrist."},{"title":"Generate Power","description":"Use hip rotation."},{"title":"Apply Ikkyo","description":"Complete with ikkyo control."}],"important_notes":[{"note":"Strong center movement needed."}]}'
    ),
(
      'ushiro-ryotedori-ikkyo',
      'ushiro-ryotedori-ikkyo',
      'grading',
      '後ろ両手取り一教',
      'Ushiro Ryotedori Ikkyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'ushiro-ryotedori',
      'ikkyo',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Before Grab","description":"Turn before fully grabbed from behind."},{"title":"Break Free","description":"Use rotation to escape hold."},{"title":"Apply Ikkyo","description":"Complete with ikkyo control."}],"important_notes":[{"note":"Anticipate and move early."}]}'
    ),
(
      'shomen-uchi-nikyo',
      'shomen-uchi-nikyo',
      'grading',
      '正面打ち二教',
      'Shomen Uchi Nikyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'shomen-uchi',
      'nikyo',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi attack."},{"title":"Control Wrist","description":"Secure nikyo grip on wrist."},{"title":"Apply Pressure","description":"Use wrist lock to control partner."}],"important_notes":[{"note":"Maintain connection through entire technique."}]}'
    ),
(
      'yokomen-uchi-nikyo',
      'yokomen-uchi-nikyo',
      'grading',
      '横面打ち二教',
      'Yokomen Uchi Nikyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'nikyo',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept Strike","description":"Enter to receive yokomen strike."},{"title":"Capture Wrist","description":"Transition to nikyo grip."},{"title":"Complete","description":"Apply nikyo and pin."}],"important_notes":[{"note":"Timing is crucial for this technique."}]}'
    ),
(
      'katadori-nikyo',
      'katadori-nikyo',
      'grading',
      '肩取り二教',
      'Katadori Nikyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'katadori',
      'nikyo',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Shoulder grabbed."},{"title":"Control Arm","description":"Control grabbing arm."},{"title":"Apply Nikyo","description":"Apply wrist lock."}],"important_notes":[{"note":"Maintain structure throughout."}]}'
    ),
(
      'shomen-uchi-sankyo',
      'shomen-uchi-sankyo',
      'grading',
      '正面打ち三教',
      'Shomen Uchi Sankyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'shomen-uchi',
      'sankyo',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi."},{"title":"Capture Wrist","description":"Transition to sankyo grip."},{"title":"Apply Sankyo","description":"Rotate wrist and control."}],"important_notes":[{"note":"Keep elbow close to body during rotation."}]}'
    ),
(
      'yokomen-uchi-sankyo',
      'yokomen-uchi-sankyo',
      'grading',
      '横面打ち三教',
      'Yokomen Uchi Sankyo',
      'Taijutsu',
      'Osae Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'sankyo',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept yokomen strike."},{"title":"Capture","description":"Control wrist and transition to sankyo."},{"title":"Apply","description":"Complete the lock and pin."}],"important_notes":[{"note":"Smooth circular movement throughout."}]}'
    ),
(
      'chudan-tsuki-sankyo',
      'chudan-tsuki-sankyo',
      'grading',
      '突き三教',
      'Chudan Tsuki Sankyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'tsuki',
      'sankyo',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Evade Thrust","description":"Enter off the line of attack."},{"title":"Control Arm","description":"Capture attacking arm."},{"title":"Apply Sankyo","description":"Rotate wrist into sankyo lock."}],"important_notes":[{"note":"Control angle of wrist rotation."}]}'
    ),
(
      'shomen-uchi-yonkyo',
      'shomen-uchi-yonkyo',
      'grading',
      '正面打ち四教',
      'Shomen Uchi Yonkyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'shomen-uchi',
      'yonkyo',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi."},{"title":"Control Wrist","description":"Transition to yonkyo grip on forearm."},{"title":"Apply Yonkyo","description":"Apply pressure point on forearm."}],"important_notes":[{"note":"Yonkyo requires precise pressure point location."}]}'
    ),
(
      'yokomen-uchi-yonkyo',
      'yokomen-uchi-yonkyo',
      'grading',
      '横面打ち四教',
      'Yokomen Uchi Yonkyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'yokomen-uchi',
      'yonkyo',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept strike."},{"title":"Control","description":"Capture wrist and transition to yonkyo."},{"title":"Apply","description":"Apply forearm pressure and pin."}],"important_notes":[{"note":"Find the pressure point on the forearm."}]}'
    ),
(
      'yokomen-uchi-gokyo',
      'yokomen-uchi-gokyo',
      'grading',
      '横面打ち五教',
      'Yokomen Uchi Gokyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'yokomen-uchi',
      'gokyo',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to receive strike."},{"title":"Reverse Grip","description":"Apply gokyo grip."},{"title":"Control","description":"Pin with reverse wrist control."}],"important_notes":[{"note":"Gokyo is primarily for knife attacks."}]}'
    ),
(
      'katatedori-shihonage',
      'katatedori-shihonage',
      'grading',
      '片手取り四方投げ',
      'Katatedori Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Beginner',
      '',
      'katatedori',
      'shihonage',
      '["7th-kyu","6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Partner grabs wrist."},{"title":"Enter and Raise","description":"Step through and raise arms."},{"title":"Execute Throw","description":"Cut down in four directions."}],"important_notes":[{"note":"Keep arms extended during throw."}]}'
    ),
(
      'shomen-uchi-shihonage',
      'shomen-uchi-shihonage',
      'grading',
      '正面打ち四方投げ',
      'Shomen Uchi Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'shomen-uchi',
      'shihonage',
      '["6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi."},{"title":"Capture and Turn","description":"Control wrist and turn."},{"title":"Execute Throw","description":"Throw in four directions."}],"important_notes":[{"note":"Enter deeply to control center."}]}'
    ),
(
      'yokomen-uchi-shihonage',
      'yokomen-uchi-shihonage',
      'grading',
      '横面打ち四方投げ',
      'Yokomen Uchi Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'shihonage',
      '["6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept yokomen."},{"title":"Redirect","description":"Redirect strike into shiho-nage."},{"title":"Execute","description":"Complete throw."}],"important_notes":[{"note":"Use circular motion throughout."}]}'
    ),
(
      'ryotedori-shihonage',
      'ryotedori-shihonage',
      'grading',
      '両手取り四方投げ',
      'Ryotedori Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'ryotedori',
      'shihonage',
      '["4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Both wrists grabbed."},{"title":"Free One Hand","description":"Use body movement to free."},{"title":"Execute","description":"Apply shiho-nage to freed arm."}],"important_notes":[{"note":"Movement comes from hips."}]}'
    ),
(
      'chudan-tsuki-shihonage',
      'chudan-tsuki-shihonage',
      'grading',
      '突き四方投げ',
      'Chudan Tsuki Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'tsuki',
      'shihonage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Evade Thrust","description":"Step off line of attack."},{"title":"Capture Arm","description":"Control punching arm."},{"title":"Execute","description":"Complete shiho-nage throw."}],"important_notes":[{"note":"Timing of entry is critical."}]}'
    ),
(
      'morotedori-shihonage',
      'morotedori-shihonage',
      'grading',
      '諸手取り四方投げ',
      'Morotedori Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'morotedori',
      'shihonage',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Two hands on one wrist."},{"title":"Break Balance","description":"Use hip power to break grip."},{"title":"Execute","description":"Apply shiho-nage."}],"important_notes":[{"note":"Strong hip rotation needed."}]}'
    ),
(
      'ushiro-ryotedori-shihonage',
      'ushiro-ryotedori-shihonage',
      'grading',
      '後ろ両手取り四方投げ',
      'Ushiro Ryotedori Shiho-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'ushiro-ryotedori',
      'shihonage',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Escape Hold","description":"Turn before fully grabbed."},{"title":"Control","description":"Secure control of one arm."},{"title":"Execute","description":"Complete shiho-nage."}],"important_notes":[{"note":"Early movement is essential."}]}'
    ),
(
      'shomen-uchi-iriminage',
      'shomen-uchi-iriminage',
      'grading',
      '正面打ち入り身投げ',
      'Shomen Uchi Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Beginner',
      '',
      'shomen-uchi',
      'iriminage',
      '["7th-kyu","6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Enter","description":"Irimi entry blending with strike."},{"title":"Turn","description":"Tenkan to redirect partner."},{"title":"Throw","description":"Enter behind and throw."}],"important_notes":[{"note":"Entry must be decisive."}]}'
    ),
(
      'yokomen-uchi-iriminage',
      'yokomen-uchi-iriminage',
      'grading',
      '横面打ち入り身投げ',
      'Yokomen Uchi Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'iriminage',
      '["6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept strike."},{"title":"Redirect","description":"Guide partner''s movement."},{"title":"Throw","description":"Complete irimi-nage."}],"important_notes":[{"note":"Control partner''s head and posture."}]}'
    ),
(
      'chudan-tsuki-iriminage',
      'chudan-tsuki-iriminage',
      'grading',
      '突き入り身投げ',
      'Chudan Tsuki Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'tsuki',
      'iriminage',
      '["4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Evade","description":"Step off line of thrust."},{"title":"Enter","description":"Irimi behind partner."},{"title":"Throw","description":"Execute irimi-nage."}],"important_notes":[{"note":"Mind the second punch."}]}'
    ),
(
      'katatedori-iriminage',
      'katatedori-iriminage',
      'grading',
      '片手取り入り身投げ',
      'Katatedori Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'katatedori',
      'iriminage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Wrist grabbed."},{"title":"Enter","description":"Irimi to partner''s side."},{"title":"Throw","description":"Complete irimi-nage."}],"important_notes":[{"note":"Use grabbed hand to maintain connection."}]}'
    ),
(
      'morotedori-iriminage',
      'morotedori-iriminage',
      'grading',
      '諸手取り入り身投げ',
      'Morotedori Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'morotedori',
      'iriminage',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Two hands on one wrist."},{"title":"Break and Enter","description":"Use body to break hold and enter."},{"title":"Throw","description":"Complete irimi-nage."}],"important_notes":[{"note":"Generate power from center."}]}'
    ),
(
      'ushiro-ryotedori-iriminage',
      'ushiro-ryotedori-iriminage',
      'grading',
      '後ろ両手取り入り身投げ',
      'Ushiro Ryotedori Irimi-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'ushiro-ryotedori',
      'iriminage',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Escape","description":"Turn before fully grabbed."},{"title":"Control","description":"Control partner''s position."},{"title":"Throw","description":"Execute irimi-nage."}],"important_notes":[{"note":"Keep moving throughout."}]}'
    ),
(
      'katatedori-kotegaeshi',
      'katatedori-kotegaeshi',
      'grading',
      '片手取り小手返し',
      'Katatedori Kote-gaeshi',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'katatedori',
      'kotegaeshi',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Wrist grabbed."},{"title":"Turn and Capture","description":"Tenkan and capture wrist."},{"title":"Apply","description":"Apply wrist turn and throw."}],"important_notes":[{"note":"Cut down with the throw."}]}'
    ),
(
      'shomen-uchi-kotegaeshi',
      'shomen-uchi-kotegaeshi',
      'grading',
      '正面打ち小手返し',
      'Shomen Uchi Kote-gaeshi',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'shomen-uchi',
      'kotegaeshi',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi."},{"title":"Capture","description":"Capture wrist."},{"title":"Apply","description":"Apply kote-gaeshi."}],"important_notes":[{"note":"Connect before capturing wrist."}]}'
    ),
(
      'yokomen-uchi-kotegaeshi',
      'yokomen-uchi-kotegaeshi',
      'grading',
      '横面打ち小手返し',
      'Yokomen Uchi Kote-gaeshi',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'yokomen-uchi',
      'kotegaeshi',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept strike."},{"title":"Capture","description":"Capture wrist from strike."},{"title":"Apply","description":"Apply kote-gaeshi."}],"important_notes":[{"note":"Smooth transition from strike to capture."}]}'
    ),
(
      'chudan-tsuki-kotegaeshi',
      'chudan-tsuki-kotegaeshi',
      'grading',
      '突き小手返し',
      'Chudan Tsuki Kote-gaeshi',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'tsuki',
      'kotegaeshi',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Evade","description":"Step off line of thrust."},{"title":"Capture","description":"Capture punching wrist."},{"title":"Apply","description":"Apply kote-gaeshi."}],"important_notes":[{"note":"Timing is critical."}]}'
    ),
(
      'ryotedori-tenchinage',
      'ryotedori-tenchinage',
      'grading',
      '両手取り天地投げ',
      'Ryotedori Tenchi-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'ryotedori',
      'tenchinage',
      '["4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Both wrists grabbed."},{"title":"Split","description":"Separate hands - heaven and earth."},{"title":"Throw","description":"Enter and throw."}],"important_notes":[{"note":"Hands go to ''heaven'' and ''earth'' simultaneously."}]}'
    ),
(
      'shomen-uchi-kokyunage',
      'shomen-uchi-kokyunage',
      'grading',
      '正面打ち呼吸投げ',
      'Shomen Uchi Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Beginner',
      '',
      'shomen-uchi',
      'kokyunage',
      '["6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive","description":"Blend with strike."},{"title":"Redirect","description":"Use breathing power to redirect."},{"title":"Throw","description":"Complete kokyu-nage."}],"important_notes":[{"note":"Use ki extension, not muscle."}]}'
    ),
(
      'yokomen-uchi-kokyunage',
      'yokomen-uchi-kokyunage',
      'grading',
      '横面打ち呼吸投げ',
      'Yokomen Uchi Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'kokyunage',
      '["5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to receive strike."},{"title":"Blend","description":"Harmonize with partner''s energy."},{"title":"Throw","description":"Complete with breath power."}],"important_notes":[{"note":"Stay relaxed throughout."}]}'
    ),
(
      'ryotedori-kokyunage',
      'ryotedori-kokyunage',
      'grading',
      '両手取り呼吸投げ',
      'Ryotedori Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'ryotedori',
      'kokyunage',
      '["4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive","description":"Both wrists grabbed."},{"title":"Lead","description":"Lead partner with ki."},{"title":"Throw","description":"Complete breath throw."}],"important_notes":[{"note":"Move from one-point."}]}'
    ),
(
      'katatedori-kokyunage',
      'katatedori-kokyunage',
      'grading',
      '片手取り呼吸投げ',
      'Katatedori Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'katatedori',
      'kokyunage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive","description":"Wrist grabbed."},{"title":"Extend","description":"Extend ki through arm."},{"title":"Throw","description":"Complete kokyu-nage."}],"important_notes":[{"note":"Hand should lead the body."}]}'
    ),
(
      'morotedori-kokyunage',
      'morotedori-kokyunage',
      'grading',
      '諸手取り呼吸投げ',
      'Morotedori Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'morotedori',
      'kokyunage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive","description":"Two hands on one wrist."},{"title":"Generate Power","description":"Draw power from hips."},{"title":"Throw","description":"Complete throw."}],"important_notes":[{"note":"Grip is opportunity, not obstacle."}]}'
    ),
(
      'ushiro-ryotedori-kokyunage',
      'ushiro-ryotedori-kokyunage',
      'grading',
      '後ろ両手取り呼吸投げ',
      'Ushiro Ryotedori Kokyu-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'ushiro-ryotedori',
      'kokyunage',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Escape","description":"Turn before fully grabbed."},{"title":"Lead","description":"Lead partner''s energy."},{"title":"Throw","description":"Complete breath throw."}],"important_notes":[{"note":"Keep extending throughout."}]}'
    ),
(
      'zagi-kokyuho',
      'zagi-kokyuho',
      'grading',
      '座技呼吸法',
      'Zagi Kokyu-ho',
      'Taijutsu',
      'Kokyu Waza',
      'Beginner',
      '',
      'ryotedori',
      'kokyuho',
      '["7th-kyu","6th-kyu","5th-kyu","4th-kyu","3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Seiza","description":"Face partner in seiza."},{"title":"Receive","description":"Wrists grabbed."},{"title":"Extend and Throw","description":"Breath power throw."}],"important_notes":[{"note":"Foundation of all Aikido."}]}'
    ),
(
      'katatedori-kokyuho',
      'katatedori-kokyuho',
      'grading',
      '片手取り呼吸法',
      'Katatedori Kokyu-ho',
      'Taijutsu',
      'Kokyu Waza',
      'Intermediate',
      '',
      'katatedori',
      'kokyuho',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive","description":"Single wrist grabbed."},{"title":"Extend Ki","description":"Extend breath power through grabbed wrist."},{"title":"Complete","description":"Complete the exercise."}],"important_notes":[{"note":"Focus on breath coordination."}]}'
    ),
(
      'ushiro-katatedori-kokyuho',
      'ushiro-katatedori-kokyuho',
      'grading',
      '後ろ片手取り呼吸法',
      'Ushiro Katatedori Kokyu-ho',
      'Taijutsu',
      'Kokyu Waza',
      'Advanced',
      '',
      'ushiro-ryotedori',
      'kokyuho',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Setup","description":"Wrist grabbed from behind."},{"title":"Extend","description":"Extend breath power."},{"title":"Complete","description":"Complete exercise."}],"important_notes":[{"note":"Use whole body."}]}'
    ),
(
      'shomen-uchi-gokyo',
      'shomen-uchi-gokyo',
      'grading',
      '正面打ち五教',
      'Shomen Uchi Gokyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'shomen-uchi',
      'gokyo',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi attack."},{"title":"Reverse Grip","description":"Apply gokyo with reverse grip."},{"title":"Control","description":"Pin with pressure on wrist keeping blade away."}],"important_notes":[{"note":"Gokyo is designed to safely disarm knife attacks."}]}'
    ),
(
      'chudan-tsuki-gokyo',
      'chudan-tsuki-gokyo',
      'grading',
      '突き五教',
      'Chudan Tsuki Gokyo',
      'Taijutsu',
      'Osae Waza',
      'Advanced',
      '',
      'tsuki',
      'gokyo',
      '["1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Evade Thrust","description":"Enter off line of thrust."},{"title":"Capture Arm","description":"Control attacking arm with reverse grip."},{"title":"Apply Gokyo","description":"Pin with gokyo keeping blade away."}],"important_notes":[{"note":"Essential for knife defense from thrust attacks."}]}'
    ),
(
      'shomen-uchi-kaitennage',
      'shomen-uchi-kaitennage',
      'grading',
      '正面打ち回転投げ',
      'Shomen Uchi Kaiten-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'shomen-uchi',
      'kaitennage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Strike","description":"Blend with shomen-uchi attack."},{"title":"Rotate","description":"Guide partner into rotation."},{"title":"Throw","description":"Complete rotary throw."}],"important_notes":[{"note":"Partner rotates around their own center."}]}'
    ),
(
      'yokomen-uchi-kaitennage',
      'yokomen-uchi-kaitennage',
      'grading',
      '横面打ち回転投げ',
      'Yokomen Uchi Kaiten-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'yokomen-uchi',
      'kaitennage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Intercept","description":"Enter to intercept yokomen strike."},{"title":"Rotate","description":"Guide partner into rotation."},{"title":"Throw","description":"Complete rotary throw."}],"important_notes":[{"note":"Use partner''s momentum to initiate rotation."}]}'
    ),
(
      'katatedori-kaitennage',
      'katatedori-kaitennage',
      'grading',
      '片手取り回転投げ',
      'Katatedori Kaiten-nage',
      'Taijutsu',
      'Nage Waza',
      'Intermediate',
      '',
      'katatedori',
      'kaitennage',
      '["3rd-kyu","2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Wrist grabbed."},{"title":"Lead and Rotate","description":"Lead partner and initiate rotation."},{"title":"Throw","description":"Complete kaiten-nage."}],"important_notes":[{"note":"Both uchi and soto variations exist."}]}'
    ),
(
      'ryotedori-kaitennage',
      'ryotedori-kaitennage',
      'grading',
      '両手取り回転投げ',
      'Ryotedori Kaiten-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'ryotedori',
      'kaitennage',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Both wrists grabbed."},{"title":"Break and Rotate","description":"Free one hand and rotate partner."},{"title":"Throw","description":"Complete rotary throw."}],"important_notes":[{"note":"Break grip using body movement."}]}'
    ),
(
      'morotedori-kaitennage',
      'morotedori-kaitennage',
      'grading',
      '諸手取り回転投げ',
      'Morotedori Kaiten-nage',
      'Taijutsu',
      'Nage Waza',
      'Advanced',
      '',
      'morotedori',
      'kaitennage',
      '["2nd-kyu","1st-kyu","shodan"]',
      '[]',
      '{"key_postures":[{"title":"Receive Grab","description":"Two hands on one wrist."},{"title":"Generate Power","description":"Use hip power to initiate rotation."},{"title":"Throw","description":"Complete kaiten-nage."}],"important_notes":[{"note":"Hip rotation is essential."}]}'
    )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  name_jp = EXCLUDED.name_jp,
  name_en = EXCLUDED.name_en,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  difficulty = EXCLUDED.difficulty,
  description = EXCLUDED.description,
  attack = EXCLUDED.attack,
  base_technique = EXCLUDED.base_technique,
  belt_levels = EXCLUDED.belt_levels,
  variants = EXCLUDED.variants,
  content = EXCLUDED.content,
  updated_at = NOW();


-- Insert Events
INSERT INTO public.events (id, title_key, date, end_date, dojo_id, description_key, image_url, event_type, instructor, related_blog_ids)
VALUES
(
      'winter-gasshuku-2026',
      'winterGasshuku2026',
      '2026-02-15',
      '2026-02-17',
      'iwama-honbu',
      'winterGasshuku2026Desc',
      '/images/events/gasshuku-winter.jpg',
      'gasshuku',
      'Hitohira Saito Sensei',
      '[]'
    ),
(
      'weapons-seminar-feb',
      'weaponsSeminarFeb',
      '2026-02-22',
      NULL,
      'takemusu-paris',
      'weaponsSeminarFebDesc',
      '/images/events/weapons-seminar.jpg',
      'seminar',
      'Daniel Toutain Sensei',
      '[]'
    ),
(
      'spring-gasshuku-2026',
      'springGasshuku2026',
      '2026-03-20',
      '2026-03-23',
      'tanrenkan-california',
      'springGasshuku2026Desc',
      '/images/events/gasshuku-spring.jpg',
      'gasshuku',
      'Miles Kessler Sensei',
      '[]'
    ),
(
      'beginner-workshop-mar',
      'beginnerWorkshopMar',
      '2026-03-08',
      NULL,
      'iwama-sweden',
      'beginnerWorkshopMarDesc',
      '/images/events/beginner-workshop.jpg',
      'workshop',
      'Ulf Evenas Sensei',
      '[]'
    ),
(
      'dan-examination-apr',
      'danExaminationApr',
      '2026-04-12',
      NULL,
      'iwama-honbu',
      'danExaminationAprDesc',
      '/images/events/dan-exam.jpg',
      'examination',
      'Hitohira Saito Sensei',
      '[]'
    ),
(
      'summer-intensive-2026',
      'summerIntensive2026',
      '2026-07-15',
      '2026-07-25',
      'iwama-honbu',
      'summerIntensive2026Desc',
      '/images/events/summer-intensive.jpg',
      'gasshuku',
      'Hitohira Saito Sensei',
      '[]'
    )
ON CONFLICT (id) DO UPDATE SET
  title_key = EXCLUDED.title_key,
  date = EXCLUDED.date,
  end_date = EXCLUDED.end_date,
  dojo_id = EXCLUDED.dojo_id,
  description_key = EXCLUDED.description_key,
  image_url = EXCLUDED.image_url,
  event_type = EXCLUDED.event_type,
  instructor = EXCLUDED.instructor,
  related_blog_ids = EXCLUDED.related_blog_ids;

